# ExploitFixer by LinsaFTW
# Please help by donating, we require funds to continue with the development.
# https://paypal.me/LinsaFTW
#
# INSTALL THE PLUGIN ON ALL BUKKIT SERVERS!
#
# Most of the check use Violations (vls), this a counter to execute different
# actions on diverse levels to allow high customization of the modules.

# Default language used by the plugin (This changes depending on the client language)
locale: "en"

# Web link used on the messages
web: "discord.gg/gF36AT3"

# Shows notifications to console and players with permissions.
notifications:
  enabled: true

  # Placeholders: %player% %ping% %check% %vls%
  message: "&c&lEF: &e%player% &7(&a%ping%ms&7) &ffailed &6%check% &7(&c%vls% vls&7)"

  # This shows extra information about blocked packets.
  debug: false

# Prevents exploits that occur on different Bukkit events.
events:
  # Prevents moving if the chunk is null. (Prevents chunk overloading)
  null_chunk: true

  # Prevents players from damaging themselves and consuming ram.
  self_damage: true

  # Prevents players from breaking ender portals.
  ender_portal_break: true

  # Prevents maps from tracking fixing many crash exploits. (The map will no longer show players their location.)
  disable_tracking: true

  # Prevents crashing when using dispensers that drop items out of the bounds.
  dispenser_crash: true

  # Prevents portal teleport spam crash.
  portal_crash: true

  # Prevents duplicating items with some inventory plugins.
  inventory_exploit: true

# Prevents the use of invalid packets to crash the server.
packets:
  enabled: true

  # Amount of vls required to start cancelling packets.
  cancel_vls: 25

  # Amount of vls to reduce per second.
  reduce_vls: 25

  # Cancels packets if the player sending them is offline.
  # This prevents duplication with auction house plugins.
  offline: true

  # This will check if integers, floats, doubles and items have an invalid size in packets.
  data:
    # Vls to add when a packet fails the check. (Set to -1 to disable)
    vls: 100

    # Maximum amount of bytes allowed per packet. (Set to -1 to disable)
    max_size: 12288

    # Maximum amount of bytes allowed per book page. (Set to -1 to disable)
    max_size_book: 300

    # Maximum amount of bytes allowed per sign line. (Set to -1 to disable)
    max_size_sign: 47

    # Maximum amount of flags allowed per packet. (Set to -1 to disable)
    max_flags: 64

    # Maximum amount of flags allowed per firework. (Set to -1 to disable)
    max_firework_flags: 12

  # Cancels book packets when a book is not in hand. (Can sometimes becaused by lag)
  # Vls to add when a packet fails the check. (Set to -1 to disable)
  book: 10

  # Cancels CustomPayload packets with invalid tags
  # Vls to add when a packet fails the check. (Set to -1 to disable)
  tag: 100

  # Checks if players send PacketPlayInWindowClick packets with invalid data.
  # Vls to add when a packet fails the check. (Set to -1 to disable)
  window_click: 100

  # Checks if players send PacketPlayInBlockPlace packets with invalid data.
  # Vls to add when a packet fails the check. (Set to -1 to disable)
  block_place: 100

  # Checks if players send PacketPlayInBlockDig packets with invalid data.
  # Vls to add when a packet fails the check. (Set to -1 to disable)
  block_dig: 100

  # Checks if players send PacketPlayInCreativeSlot packets without creative.
  # Vls to add when a packet fails the check. (Set to -1 to disable)
  set_creative_slot: 100

  # This option adds vls per byte received.
  # This works as a packet limiter feature.
  # Violations to add per byte received. (Set to -1 to disable)
  byte_multiplier: 0.0001

  # Set a permission for some players to bypass this check. (Uncomment to enable)
  # WARNING: Players with this permission can crash and corrupt worlds FOREVER with hacked clients.
  #bypass-permission: "exploitfixer.packets.bypass"

  # Violations to add when a normal packet is received from a player.
  # This works as a packet limiter feature.
  # Unlisted packets are considered as "PacketPlayInOther" by default.
  # Remember to take a look at byte_multiplier option.
  rate_multipliers:
    PacketPlayInOther: 0.1
    MC|BSign: 4.5
    MC|BEdit: 4.5
    MC|BOpen: 4.5
    PacketPlayInAutoRecipe: 10
    PacketPlayInUpdateSign: 5
    PacketPlayInAbilities: 0.25
    PacketPlayInArmAnimation: 0.125
    PacketPlayInBlockDig: 0.125
    PacketPlayInBlockPlace: 0.5
    PacketPlayInCustomPayload: 0.01
    PacketPlayInEntityAction: 0.5
    PacketPlayInFlying: 0.25
    PacketPlayInLook: 0.4
    PacketPlayInSteerVehicle: 0.05
    PacketPlayInPositionLook: 0.05
    PacketPlayInPosition: 0.2
    PacketPlayInSetCreativeSlot: 0.15
    PacketPlayInSettings: 0.1
    PacketPlayInTabComplete: 0.75
    PacketPlayInUseEntity: 0.5
    PacketPlayInUseItem: 0.1
    PacketPlayInWindowClick: 0.45

  # These packets will be completely cancelled.
  blacklist:
    - "PacketPlayInAutoRecipe"

  # Placeholders: %player%, %vls%, %ping%, %check%
  # Commands to run when a player reaches certain violation level.
  violations:
    25:
      - "notification"
    50:
      - "notification"
    75:
      - "notification"
    100:
      - "notification"
      - "kick"

# Removes custom/invalid NBT tags from items to prevent harm to your server.
# This prevents creative mode players from corrupting worlds FOREVER and crashing the server.
# This checks only applies to creative mode players.
creative-items-fix:
  enabled: true

  # Maximum stack size obtainable with creative packets. (-1 to allow anything)
  max-stack-size: 64

  # Maximum enchant level obtainable with creative packets.
  # -1 removes all enchants, 0 forces vanilla values
  enchant-limit: 0

  # Whitelist already created items to improve performance and stability.
  # Items created with commands will not be checked when enabled.
  # Set to false if your server has already created crasher items.
  whitelist-items: true

  # List of materials that are blocked from Creative.
  blacklist:
    - "END_PORTAL"
    - "NETHER_PORTAL"
  #  - "BARRIER"
  #  - "COMMAND_BLOCK"

  # Set a permission for some players to bypass this check. (Uncomment to enable)
  # WARNING: Players with this permission can crash and corrupt worlds FOREVER with hacked clients.
  #bypass-permission: "exploitfixer.itemsfix.bypass"

# Checks if players try to crash/exploit the server with commands.
commands:
  enabled: true

  # Commands that are exempt from this server.
  commands:
    # WorldEdit exploit
    - "//calc"
    - "//calculate"
    - "//eval"
    - "//evaluate"
    - "//solve"
    # HolographicDisplays exploit
    - "/hd readtext"
    - "/holo readtext"
    - "/hologram readtext"
    - "/holograms readtext"
    - "/holographicdisplays readtext"
    # PermissionsEx exploit
    - "/pex promote"
    - "/pex demote"
    - "/promote"
    - "/demote"
    - "/execute"
    # Multiverse exploit
    - "/mv ^"
    - "/mv help <"
    - "/mvhelp <"
    - "/$"

  # Set a permission for some players to bypass this check. (Uncomment to enable)
  # WARNING: Players with this permission can crash and corrupt worlds FOREVER with hacked clients.
  #bypass-permission: "exploitfixer.commands.bypass"

  # Placeholders: %player%
  punishments:
    - "notification"
    - "kick"
