name: ${name}
description: ${description}
author: ${author}
version: ${version}
url: ${url}
main: dev._2lstudios.exploitfixer.ExploitFixer
api: "1.13"
api-version: "1.13"
softdepend: [HamsterAPI]
commands:
  exploitfixer:
    description: The main ExploitFixer command
    usage: /exploitfixer
    aliases: [ef]
